# Generated by Django 5.2.8 on 2025-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiccionestic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='consent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.CharField(choices=[('EC', 'Ecuador'), ('CL', 'Chile')], default='--', max_length=2),
        ),
    ]
