# Generated by Django 5.2.8 on 2025-11-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiccionestic', '0002_participant_consent_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='consent_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='consent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
