# Generated by Django 5.2.8 on 2025-11-24 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiccionestic', '0003_alter_participant_consent_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='career',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='father_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='father_education_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gpa_last_semester',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='income_sources',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='living_with',
            field=models.CharField(blank=True, choices=[('alone', 'Solo/a'), ('mother', 'Con mamá'), ('father', 'Con papá'), ('both_parents', 'Con ambos padres'), ('parents_siblings', 'Con padres y hermanos'), ('parents_siblings_grandparents', 'Con padres, hermanos y abuelos'), ('extended_family', 'Con padres, hermanos, abuelos y tíos'), ('other', 'Otros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='living_with_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('free_union', 'Unión libre'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a'), ('separated', 'Separado/a')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='mother_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='mother_education_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='repeated_cycles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='repeated_cycles_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='residence_sector',
            field=models.CharField(blank=True, choices=[('urban', 'Urbano'), ('rural', 'Rural')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='socioeconomic_level',
            field=models.CharField(blank=True, choices=[('high', 'Alto'), ('medium', 'Medio'), ('low', 'Bajo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
