# Generated by Django 5.2.8 on 2025-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiccionestic', '0004_participant_age_participant_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='father_education_level',
            field=models.CharField(blank=True, choices=[('none', 'Ninguno'), ('primary', 'Primaria'), ('secondary', 'Secundaria'), ('college', 'Superior'), ('postgraduate', 'Postgrado')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mother_education_level',
            field=models.CharField(blank=True, choices=[('none', 'Ninguno'), ('primary', 'Primaria'), ('secondary', 'Secundaria'), ('college', 'Superior'), ('postgraduate', 'Postgrado')], max_length=200, null=True),
        ),
    ]
