# Generated by Django 5.2.8 on 2025-11-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiccionestic', '0005_alter_participant_father_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='current_semester',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=50, null=True),
        ),
    ]
